spring:
  datasource:
    primary:
      url: jdbc:mysql://119.23.55.112:3306/sys_permission_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: lnlr
      password: lnlr
    slave:
      url: jdbc:mysql://119.23.55.112:3306/sys_permission_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: lnlr
      password: lnlr